### ISSUE TITLE
BUG - Random server crash on signup

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/Mountain_Guarder#109]
**Describe the bug**
@maitian352 tried to create an account but it crashed the server instead

**To Reproduce**
1. create account

**Expected behavior**
it bypassed all crash protections

**Screenshots**
N/A

**Environment**
 - Browser N/A
 - Version v0.5.4

**Logs**
server:
```
2021-11-24T01:31:14.621611+00:00 heroku[web.1]: Unidling
2021-11-24T01:31:14.854200+00:00 heroku[web.1]: State changed from down to starting
2021-11-24T01:31:18.366588+00:00 heroku[web.1]: Starting process with command `npm start`
2021-11-24T01:31:20.762089+00:00 app[web.1]:
2021-11-24T01:31:20.762111+00:00 app[web.1]: > mountain_guarder@0.5.4 start /app
2021-11-24T01:31:20.762111+00:00 app[web.1]: > node app.js
2021-11-24T01:31:20.762112+00:00 app[web.1]:
2021-11-24T01:31:20.845434+00:00 app[web.1]: Mountain Guarder v0.5.4 copyright (C) Radioactive64 2021
2021-11-24T01:31:20.846879+00:00 app[web.1]: [1:31] Starting server...
2021-11-24T01:31:21.322490+00:00 app[web.1]: [1:31] Connecting to database...
2021-11-24T01:31:21.667396+00:00 app[web.1]: [1:31] Server started.
2021-11-24T01:31:21.690020+00:00 app[web.1]: [1:31] ---------------------------
2021-11-24T01:31:22.255713+00:00 heroku[web.1]: State changed from starting to up
2021-11-24T01:33:16.692015+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'username' of undefined
2021-11-24T01:33:16.692023+00:00 app[web.1]: at Socket.<anonymous> (/app/server/entity.js:697:55)
2021-11-24T01:33:16.692024+00:00 app[web.1]: at Socket.emit (events.js:400:28)
2021-11-24T01:33:16.692024+00:00 app[web.1]: at Socket.emitUntyped (/app/node_modules/socket.io/dist/typed-events.js:69:22)
2021-11-24T01:33:16.692024+00:00 app[web.1]: at /app/node_modules/socket.io/dist/socket.js:428:39
2021-11-24T01:33:16.692025+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:77:11)
2021-11-24T01:33:16.692025+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-11-24T01:33:16.692257+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-11-24T01:33:16.692478+00:00 app[web.1]: (node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-11-24T01:33:18.428328+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'username' of undefined
2021-11-24T01:33:18.428336+00:00 app[web.1]: at Socket.<anonymous> (/app/server/entity.js:697:55)
2021-11-24T01:33:18.428337+00:00 app[web.1]: at Socket.emit (events.js:400:28)
2021-11-24T01:33:18.428337+00:00 app[web.1]: at Socket.emitUntyped (/app/node_modules/socket.io/dist/typed-events.js:69:22)
2021-11-24T01:33:18.428338+00:00 app[web.1]: at /app/node_modules/socket.io/dist/socket.js:428:39
2021-11-24T01:33:18.428339+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:77:11)
2021-11-24T01:33:18.428504+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2021-11-24T01:33:18.764363+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'username' of undefined
2021-11-24T01:33:18.764371+00:00 app[web.1]: at Socket.<anonymous> (/app/server/entity.js:697:55)
2021-11-24T01:33:18.764371+00:00 app[web.1]: at Socket.emit (events.js:400:28)
2021-11-24T01:33:18.764372+00:00 app[web.1]: at Socket.emitUntyped (/app/node_modules/socket.io/dist/typed-events.js:69:22)
2021-11-24T01:33:18.764372+00:00 app[web.1]: at /app/node_modules/socket.io/dist/socket.js:428:39
2021-11-24T01:33:18.764373+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:77:11)
2021-11-24T01:33:18.764542+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
2021-11-24T01:33:19.038747+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'username' of undefined
2021-11-24T01:33:19.038749+00:00 app[web.1]: at Socket.<anonymous> (/app/server/entity.js:697:55)
2021-11-24T01:33:19.038749+00:00 app[web.1]: at Socket.emit (events.js:400:28)
2021-11-24T01:33:19.038750+00:00 app[web.1]: at Socket.emitUntyped (/app/node_modules/socket.io/dist/typed-events.js:69:22)
2021-11-24T01:33:19.038750+00:00 app[web.1]: at /app/node_modules/socket.io/dist/socket.js:428:39
2021-11-24T01:33:19.038751+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:77:11)
2021-11-24T01:33:19.038752+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
2021-11-24T01:33:19.216294+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'username' of undefined
2021-11-24T01:33:19.216297+00:00 app[web.1]: at Socket.<anonymous> (/app/server/entity.js:697:55)
2021-11-24T01:33:19.216298+00:00 app[web.1]: at Socket.emit (events.js:400:28)
2021-11-24T01:33:19.216299+00:00 app[web.1]: at Socket.emitUntyped (/app/node_modules/socket.io/dist/typed-events.js:69:22)
2021-11-24T01:33:19.216299+00:00 app[web.1]: at /app/node_modules/socket.io/dist/socket.js:428:39
2021-11-24T01:33:19.216300+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:77:11)
2021-11-24T01:33:19.220052+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
2021-11-24T01:37:49.262614+00:00 app[web.1]: [1:37] SERVER ENCOUNTERED A FATAL ERROR. STOP CODE:
2021-11-24T01:37:49.264574+00:00 app[web.1]: Error: data must be a string or Buffer and salt must either be a salt string or a number of rounds
2021-11-24T01:37:49.264576+00:00 app[web.1]: at Object.hashSync (/app/node_modules/bcrypt/bcrypt.js:95:15)
2021-11-24T01:37:49.264577+00:00 app[web.1]: at writeCredentials (/app/server/database.js:176:40)
2021-11-24T01:37:49.264578+00:00 app[web.1]: at Object.signup (/app/server/database.js:56:32)
2021-11-24T01:37:49.264579+00:00 app[web.1]: at runMicrotasks (<anonymous>)
2021-11-24T01:37:49.264579+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-11-24T01:37:49.264579+00:00 app[web.1]: at async Socket.<anonymous> (/app/server/entity.js:740:38)
2021-11-24T01:37:49.264840+00:00 app[web.1]: [1:37] STOP.
2021-11-24T01:37:49.265590+00:00 app[web.1]: If this issue persists, please submit a bug report on GitHub with a screenshot of this screen and/or logfiles before this.
2021-11-24T01:37:49.265647+00:00 app[web.1]: Press ENTER or CTRL+C to exit.
2021-11-24T01:37:49.266083+00:00 app[web.1]: [1:37] SERVER ENCOUNTERED A FATAL ERROR. STOP CODE:
2021-11-24T01:37:49.266408+00:00 app[web.1]: Error: Client was closed and is not queryable
2021-11-24T01:37:49.266409+00:00 app[web.1]: at /app/node_modules/pg/lib/client.js:570:27
2021-11-24T01:37:49.266410+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:77:11)
2021-11-24T01:37:49.266614+00:00 app[web.1]: [1:37] STOP.
2021-11-24T01:37:49.266960+00:00 app[web.1]: If this issue persists, please submit a bug report on GitHub with a screenshot of this screen and/or logfiles before this.
2021-11-24T01:37:49.267019+00:00 app[web.1]: Press ENTER or CTRL+C to exit.
2021-11-24T01:37:49.267264+00:00 app[web.1]: [1:37] Failed to sign up!
```

**Comment by definitely-nobody-is-here** [comment]
it doesn't actually happen to me, it seems like it was a one-time thing

**Comment by definitely-nobody-is-here** [comment]
the database had an error. Heroku stuff.

**Comment by maitian352** [comment]
It still happens.

**Comment by definitely-nobody-is-here** [comment]
hasn't happened the whole time while testing.
