### ISSUE TITLE
BUG - socket.emit crashes server

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/Mountain_Guarder#111]
**Describe the bug**
some socket.emits with no attached data crashes the server

**To Reproduce**
1. open mountain guarder
2. open console
3. socket.emit('mouseMove')
4. server crash

**Expected behavior**
crash protection/anticheat

**Screenshots**
![image](https://user-images.githubusercontent.com/67865358/143157498-5ba79ab2-66e7-4460-a1bc-bffab15b5263.png)

**Environment**
 - Browser chrome 96
 - Version v0.5.4

**Logs**
```
2021-11-24T01:54:29.071539+00:00 app[web.1]: self.mouseX = data.x;
2021-11-24T01:54:29.071539+00:00 app[web.1]: ^
2021-11-24T01:54:29.071540+00:00 app[web.1]:
2021-11-24T01:54:29.071542+00:00 app[web.1]: TypeError: Cannot read property 'x' of undefined
2021-11-24T01:54:29.071543+00:00 app[web.1]: at Socket.<anonymous> (/app/server/entity.js:833:28)
2021-11-24T01:54:29.071544+00:00 app[web.1]: at Socket.emit (events.js:400:28)
2021-11-24T01:54:29.071545+00:00 app[web.1]: at Socket.emitUntyped (/app/node_modules/socket.io/dist/typed-events.js:69:22)
2021-11-24T01:54:29.071545+00:00 app[web.1]: at /app/node_modules/socket.io/dist/socket.js:428:39
2021-11-24T01:54:29.071546+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:77:11)
2021-11-24T01:54:29.080470+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-11-24T01:54:29.080637+00:00 app[web.1]: npm ERR! errno 1
2021-11-24T01:54:29.084240+00:00 app[web.1]: npm ERR! mountain_guarder@0.5.4 start: `node app.js`
2021-11-24T01:54:29.084281+00:00 app[web.1]: npm ERR! Exit status 1
2021-11-24T01:54:29.084334+00:00 app[web.1]: npm ERR!
2021-11-24T01:54:29.084375+00:00 app[web.1]: npm ERR! Failed at the mountain_guarder@0.5.4 start script.
2021-11-24T01:54:29.084409+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-11-24T01:54:29.088851+00:00 app[web.1]:
2021-11-24T01:54:29.088922+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-11-24T01:54:29.088956+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-11-24T01_54_29_084Z-debug.log
2021-11-24T01:54:29.207960+00:00 heroku[web.1]: Process exited with status 1
2021-11-24T01:54:29.317320+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by maitian352** [comment]
Not fixed. It still happens.

**Comment by definitely-nobody-is-here** [comment]
#84

**Comment by definitely-nobody-is-here** [comment]
> Not fixed. It still happens.

shut up I haven't pushed yet. If you don't see it on the changelogs its not fixed

**Comment by maitian352** [comment]
LOL Crashed MOUNTAIN GUARDER AGAIN!

![image](https://user-images.githubusercontent.com/68207888/145713652-3814a26c-919f-46d3-9171-d9ac798cb26a.png)

**Comment by definitely-nobody-is-here** [comment]
Huh, wierd how you forgot the in-progress and will-do labels exist.

**Comment by maitian352** [comment]
Still not fixed:
`socket.emit('item')` in menu crashes it.

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/147486426-36a9255c-601a-4568-bb8e-a45dc1e73f66.png)
yeah right

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/147515650-c4d5b22f-d296-431e-b071-7ffce3dce586.png)
![image](https://user-images.githubusercontent.com/68207888/147515652-168cfbf2-6214-4e8e-876f-0201ef976402.png)
yeah right

**Comment by definitely-nobody-is-here** [comment]
I made a typo.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/147695745-89562a8c-2946-457a-96eb-9980ea6905c3.png)

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/147970530-c9a95523-a007-470d-a902-791db856ad02.png)
