### ISSUE TITLE
VULNERABILITY - socket.emit('item', null); crashes

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/Mountain_Guarder#225]
**Describe the bug**
Putting `socket.emit('item', null);` can still crash the server

**To Reproduce**
1. `socket.emit('item', null);` in console
2. crash

**Screenshots**
See logs

**Environment**
 - Version v0.9.1

**Logs**
```
2022-03-24T01:39:22.564817+00:00 app[web.1]: Mountain Guarder v0.9.1 copyright (C) Radioactive64 2022
2022-03-24T01:39:22.565536+00:00 app[web.1]: [1:39] Starting server...
2022-03-24T01:39:22.781231+00:00 app[web.1]: [1:39] Connecting to database...
2022-03-24T01:39:22.941323+00:00 app[web.1]: [1:39] Server started.
2022-03-24T01:39:22.941648+00:00 app[web.1]: [1:39] ---------------------------
2022-03-24T01:39:23.113582+00:00 heroku[web.1]: State changed from starting to up
2022-03-24T01:39:34.559689+00:00 app[web.1]: [1:39] suvanth joined the game
2022-03-24T01:39:41.187293+00:00 app[web.1]: [1:39] SERVER ENCOUNTERED A CATASTROPHIC ERROR. STOP CODE:
2022-03-24T01:39:41.189030+00:00 app[web.1]: TypeError: Cannot read properties of null (reading 'data')
2022-03-24T01:39:41.189031+00:00 app[web.1]: at Socket.<anonymous> (/app/server/inventory.js:21:47)
2022-03-24T01:39:41.189031+00:00 app[web.1]: at Socket.emit (node:events:526:28)
2022-03-24T01:39:41.189032+00:00 app[web.1]: at Socket.emitUntyped (/app/node_modules/socket.io/dist/typed-events.js:69:22)
2022-03-24T01:39:41.189033+00:00 app[web.1]: at /app/node_modules/socket.io/dist/socket.js:466:39
2022-03-24T01:39:41.189033+00:00 app[web.1]: at processTicksAndRejections (node:internal/process/task_queues:78:11)
2022-03-24T01:39:41.189144+00:00 app[web.1]: [1:39] [!] SERVER ENCOUNTERED A CATASTROPHIC ERROR. [!]
2022-03-24T01:39:41.191295+00:00 app[web.1]: [1:39] Cannot read properties of null (reading 'data')
2022-03-24T01:39:41.192502+00:00 app[web.1]: [1:39] STOP.
2022-03-24T01:39:41.192892+00:00 app[web.1]: If this issue persists, please submit a bug report on GitHub with a screenshot of this screen and/or logfiles before this.
2022-03-24T01:39:41.192913+00:00 app[web.1]: Press ENTER or CTRL+C to exit.
2022-03-24T01:39:41.193372+00:00 app[web.1]: [1:39] Heroku server detected, automatically stopping server.
2022-03-24T01:39:41.331657+00:00 heroku[web.1]: Process exited with status 1
2022-03-24T01:39:41.436257+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by definitely-nobody-is-here** [comment]
There are also a number of other similar issues with no null exceptions.
This is because JS interprets `null` as an object
![image](https://user-images.githubusercontent.com/67865358/159826822-bc44743e-4112-43fd-a08e-afa36cd6809d.png)

**Comment by Suvanth-Erranki** [comment]
Using undefined or null for any socket.emit message will crash the server, due to improper exception handling and catch null/undefined objects. Also, I'm disappointed that you did not credit me.
